version: '2'
services:
 application:
    build:
      context: resources/data
      dockerfile: application.Dockerfile
    command: sleep infinity
 tomcat:
    build:
      context: resources/tomcat
      dockerfile: tomcat.Dockerfile
    command: /usr/libexec/tomcat/server start -DFOREGROUND
    depends_on: [ "application" ]
    volumes_from: [ "application" ]
    expose: [ "8080" ]
    ports: [ "127.0.0.1:8080:8080" ]
 web:
    build:
      context: resources/nginx
      dockerfile: web.Dockerfile
    command: nginx
    depends_on: [ "tomcat" ]
    expose: [ "80" ]
    ports: [ "127.0.0.1:80:80" ]

