version: '2'
services:
  app:
    build:
      context: .
      dockerfile: application.Dockerfile
  tomcat:
    build:
      context: .
      dockerfile: tomcat.Dockerfile
    depends_on:
      - app
    volumes_from:
      - app
  nginx:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - tomcat
    ports:
      - "80:80"
    links:
      - "tomcat:tomcat"
