version: '2'
services:
 app:
     build:
       context: .
       dockerfile: application.Dockerfile
     command: sleep infinity

 tomcat:
     build:
       context: .
       dockerfile: tomcat.Dockerfile
     command: /usr/libexec/tomcat/server start 
     depends_on: [ "app" ]
     volumes_from: [ "app" ]
   
 nginx:
     build:
       context: .
       dockerfile: web.Dockerfile
     command: nginx -g 'daemon off;'
     depends_on: [ "tomcat" ]
     expose: [ "80" ]
     ports: ["127.0.0.1:80:80"]

     
