node('dockerhost'){
stage('Building') {
  sh 'rm -rf ./*'        
  git branch: 'henadzi_pashuto2', url: 'https://github.com/aion3181/docker.git'
  sh 'mv docker-2/initial/* ./'
docker.image('day2_gradle').inside {
  sh 'gradle build'
}
}
stage('Deploying') {
  sh 'mv docker-2/deploy/docker-compose.yml ./'
  sh 'mv docker-2/deploy/test.Dockerfile ./'
  sh 'docker-compose up -d'
}
stage('Check') {
  sh 'sleep 8 && curl -IL http://127.0.0.1:8081'
  sh 'docker-compose stop test'
}
}

