version: '2'
services:
 app:
  build:
   context: .
   dockerfile: app.Dockerfile
  volumes:
      - /home/student/dockerpop/pipeline/workspace/job1/docker-2/build/libs/:/opt/
  ports: 
      - 8086:8080
    
    
      

 
