version: '2'
services:
 app:
  build:
   context: .
   dockerfile: app.Dockerfile
  volumes:
      - /home/student/workspace/spring_boot_job/docker-2/build/libs:/opt/
  ports: 
      - 127.0.0.1:8080:8080
    
    
      

 
