version: '2'
services:
 jar:
  build:
   context: .
   dockerfile: jar.Dockerfile
  volumes:
      - /home/student/dockerpop/workspace/workspace/job1/build/libs/:/opt/
  ports: 
      - 127.0.0.1:8081:8080
    
    
      

 
