version: '2'
services:
 jar:
  build:
   context: .
   dockerfile: app.Dockerfile
  volumes:
      - /home/student/dockerpop/pipeline/workspace/job1/docker-2/build/libs/:/opt/
  ports: 
      - 8081:8080
