version: '2'
services:
 jar:
  build:
   context: .
   dockerfile: jar.Dockerfile
  volumes:
      - /home/student/jenkins/pipeline/workspace/spring-boot\ application/docker-2/build/libs/:/opt/
  ports: 
      - 127.17.0.2:8080:8080
