node('epbyminw3088.minsk.epam.com'){
stage('Building') {
  sh 'rm -rf ./*'
  git branch: 'artsiom_aksionkin-2', url: 'https://github.com/artem-aksenkin/docker.git'
  sh 'cp docker-2/initial/* ./'
docker.image('jenkins/gradle:1.0').inside {
  sh 'gradle build'
}
}
stage('Deploying') {
  sh 'mv docker-2/docker-compose.yml ./'
  sh 'mv docker-2/spring.Dockerfile ./'
  sh 'docker-compose up -d'
}
stage('Check') {
  sh 'sleep 8 && curl -IL http://127.0.0.1:8081'
  sh 'docker-compose stop spring'
}
}