version: '2'
services:
 spring:
    build:
      context: .
      dockerfile: spring.Dockerfile
    ports: [ "127.0.0.1:8081:8080" ]
    volumes:
      - /home/student/workspace/jenkins_home/workspace/Docker-day2/initial/build/libs:/spring

