version: '2'
services:
 spring:
    build:
      context: .
      dockerfile: spring.Dockerfile
    ports: [ "127.0.0.1:8081:8080" ]
    volumes:
      - /var/jenkins/workspace/Build Spring/initial/build/libs:/spring

