version: '2'
services:
 datavolume:
    build:
      context: ./datavolume
      dockerfile: application.Dockerfile
    command: sleep infinity
 tomcat:
    build:
      context: ./tomcat
      dockerfile: tomcat.Dockerfile
    command: /usr/libexec/tomcat/server start
    depends_on: [ "datavolume" ]
    volumes_from: [ "datavolume" ]
 web:
    build:
      context: ./nginx
      dockerfile: web.Dockerfile
    command: ["nginx", "-g", "daemon off;"]
    depends_on: [ "tomcat" ]
    expose: [ "80" ]
    ports: [ "127.0.0.1:80:80" ]
